services:
  # Django App
  blog_w_authentication_backend:
   container_name: django_blog_w_authentication
   build: .
   command: uvicorn core.asgi:application --host 0.0.0.0 --port 8004 --reload
   volumes:
     - .:/app
   ports:
     - 8004:8004
   depends_on:
     - blog_w_authentication_django_redis
     - blog_w_authentication_django_db
    
  # Redis
  blog_w_authentication_django_redis:
   image: redis
   container_name: blog_w_authentication_django_redis
   ports:
    - 6379:6381
  
  # Database
  blog_w_authentication_django_db:
    image: postgres
    container_name: postgresql_blog_w_authentication
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5434
    volumes:
      - .dbdata:/var/lib/postgresql
  

  celery_worker:
    container_name: blog_celery_worker
    build: .
    command: celery -A core worker --loglevel=info 
    volumes:
      - .:/app
    ports:
      - "8006:8006"
    depends_on:
     - blog_w_authentication_django_redis
     - blog_w_authentication_django_db

  celery_beat:
    container_name: blog_celery_beat
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    depends_on:
     - blog_w_authentication_django_redis
     - blog_w_authentication_django_db