# Generated by Django 4.2.16 on 2025-03-20 12:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_post_user_postanalytics_comments_postanalytics_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='postinteraccion',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postinteraccion',
            name='device_type',
            field=models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postinteraccion',
            name='hour_of_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postinteraccion',
            name='interaction_category',
            field=models.CharField(choices=[('passive', 'Passive'), ('active', 'Active')], default='passive', max_length=10),
        ),
        migrations.AddField(
            model_name='postinteraccion',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postinteraccion',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='postview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.post'),
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('post', 'user', 'ip_address')},
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plataform', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram')], max_length=50, null=True)),
                ('timestapm', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='blog.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='postinteraccion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postinteraccion',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaccion', to='blog.comment'),
        ),
        migrations.AlterUniqueTogether(
            name='postinteraccion',
            unique_together={('user', 'post', 'interaction_type', 'comment')},
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestapm', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestapm'],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
