# Generated by Django 4.2.16 on 2025-03-20 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_alter_postview_options_postinteraccion_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraccion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post_interaccion', to=settings.AUTH_USER_MODEL),
        ),
    ]
