# Generated by Django 4.2.16 on 2025-04-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_postinteraccion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
