# Generated by Django 4.2.16 on 2025-03-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useraccount_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='login_otp_used',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
