# Generated by Django 4.2.16 on 2025-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_useraccount_login_otp_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('helper', 'Helper'), ('editor', 'Editor'), ('customer', 'Customer'), ('seller', 'Seller')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
